### ISSUE TITLE
💥 Type exports for ContextT, LogDNABrowserOptionsT, ILogDNABrowserLogger (and others) broken

### ISSUE THREAD

**Issue by prescience-data** [logdna/logdna-browser#7]
## Problem

Cannot get visibility on exported types.

## Cause

I believe something is getting mangled during Rollup.

This is your `dist/types/index.d.ts` file, which appears to circularly reference itself on line 1, and does not export the types it is looking for.

However, those types _**are**_ exported from `src/index.d.ts` (as seen in the screenshot), thus my inference that something must be occurring during Rollup.

```typescript
import { ContextT, LogDNABrowserOptionsT, ILogDNABrowserLogger } from './index.d';
declare class LogDNABrowserLogger implements ILogDNABrowserLogger {
    Plugins: {
        PerformanceMeasurePlugin: typeof import("./plugins/performance-measure").default;
    };
    private context;
    private logger?;
    private sessionManager;
    private sampleRateScore;
    private staticContext;
    private plugins;
    private options;
    init(ingestionKey: string, options?: LogDNABrowserOptionsT): LogDNABrowserLogger;
    addContext(context: ContextT): LogDNABrowserLogger;
    setSessionId(sessionId: string): LogDNABrowserLogger;
    clearContext(): void;
    error(message: any, lineContext?: object): void;
    warn(message: any, lineContext?: object): void;
    debug(message: any, lineContext?: object): void;
    info(message: any, lineContext?: object): void;
    log(message: any, lineContext?: object): void;
    captureError(error: Error | ErrorEvent, lineContext?: object): void;
    registerMethod(name: string, fn: Function): void;
    private formatMessageForDebug;
    private registerDefaultPlugins;
    private registerPlugin;
    private registerPlugins;
    private logLines;
    private getStackTrace;
    /**
     * Fetches information about the context that is unlikely to change during the session (ex. browser)
     */
    private getStaticContext;
    /**
     * Fetches information about the context that is likely to change during the session (ex. window location)
     */
    private getDynamicContext;
}
declare const _default: LogDNABrowserLogger;
export default _default;


```
## Error 

```text
TS2614: Module '"../../node_modules/@logdna/browser/dist/types"' has no exported member 'LogDNABrowserOptionsT'.
```

## Screenshot

![image](https://user-images.githubusercontent.com/65471523/117558239-e9ef9700-b0be-11eb-9ef0-5d236ebf2fb5.png)

**Comment by TerryMooreII** [comment]
@prescience-data Typescript support has been fixed in the latest release v1.1.1

**Comment by prescience-data** [comment]
Hi @TerryMooreII 

Unfortunately, this does still not have the exports provided.

![image](https://user-images.githubusercontent.com/65471523/118891455-10c18f00-b943-11eb-82ad-acfdf059c068.png)

This is the current `dist` export on `1.1.1`:
![image](https://user-images.githubusercontent.com/65471523/118891344-0901ea80-b943-11eb-8983-7a941796d064.png)

![image](https://user-images.githubusercontent.com/65471523/118892155-d1477280-b943-11eb-8bd0-436be7a64b34.png)



I can do a PR if you like?

**Comment by michaelshi-logdna** [comment]
hey @prescience-data really sorry to hear that it's still not working. I've been digging with @TerryMooreII a bit looking at the issue and we can't seem to reproduce the missing default type that it shows in your IDE currently.

On 1.1.1 we're seeing the default property being exported properly from TS, and we're not sure how to reproduce the issue you're running into. (Currently running TS version 4.2.4 within VS Code, this is a Svelte example TS project installed via yarn, but tested with create-react-app as well)

![image](https://user-images.githubusercontent.com/58235743/119050024-27350e00-b976-11eb-83bf-2c4a734fbc21.png)

I'm wondering if it's possible there's something poorly cached in your TS server and if you've tried restarting the TS server, or if there's an issue in lower versions of TS.

Could you try restarting your TS server and see if that resolves the issue, or share what version of TS you're currently running?

If you know/see an issue in our rollup config that's causing the types to go in the wrong place as well, would appreciate if you can point where you're seeing the issue and we can try addressing that as well.

**Comment by prescience-data** [comment]
I pushed a PR you can check out that shows the issue 🎯🚀

**Comment by prescience-data** [comment]
Essentially, I would generally expect to be able to destructure all the types out of the export as:
```typescript
import type { ILogDNABrowserLogger, LogDNABrowserOptionsT, LogType } from "@logdna/browser"

```
